logging:
  level: INFO

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9010

# Define OAuth settings
oauthSuccessUrl: http://agile-scrubland-4645.herokuapp.com/oauth/verify

oauth:
    prefix: twitter.com
    key: zmMHFOzjxsIEezXLePPJaNqPs
    secret: lsln4Suw8jCrOyxA0Fso7TsMJeoAWVVYL2xMyLI14wvWUg6aJy

