logging:
  level: INFO

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin

# Define OAuth settings
oauthSuccessUrl: http://placeholder.com:9010/oauth/verify

oauth:
    prefix: twitter.com
    key: zmMHFOzjxsIEezXLePPJaNqPs
    secret: lsln4Suw8jCrOyxA0Fso7TsMJeoAWVVYL2xMyLI14wvWUg6aJy