logging:
  level: INFO

server:
  applicationConnectors:
  - type: http
    port: 9010

# Define OAuth settings
oauthSuccessUrl: http://placeholder.com:9010/oauth/verify

oauth:
    prefix: twitter.com
    key: zmMHFOzjxsIEezXLePPJaNqPs
    secret: lsln4Suw8jCrOyxA0Fso7TsMJeoAWVVYL2xMyLI14wvWUg6aJy